/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yao' at '10/11/16 3:20 PM' with Gradle 2.8
 *
 * @author yao, @date 10/11/16 3:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
